package database

import "github.com/filipegms5/pokedex-backend/models"

var PokemonList = []models.Pokemon{
	{
		Name:     "Bulbasaur",
		Info:     "Bulbasaur can be seen napping in bright sunlight. There is a seed on its back. By soaking up the sun’s rays, the seed grows progressively larger.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/001.png",
		Types:    []models.Type{{Id: 5}, {Id: 8}},
	},
	{
		Name:     "Ivysaur",
		Info:     "There is a bud on this Pokémon’s back. To support its weight, Ivysaur’s legs and trunk grow thick and strong. If it starts spending more time lying in the sunlight, it’s a sign that the bud will bloom into a large flower soon.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/002.png",
		Types:    []models.Type{{Id: 5}, {Id: 8}},
	},
	{
		Name:     "Venusaur",
		Info:     "There is a large flower on Venusaur’s back. The flower is said to take on vivid colors if it gets plenty of nutrition and sunlight. The flower’s aroma soothes the emotions of people.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/003.png",
		Types:    []models.Type{{Id: 5}, {Id: 8}},
	},
	{
		Name:     "Charmander",
		Info:     "The flame on its tail indicates Charmander's life force. If it is healthy, the flame burns brightly.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/004.png",
		Types:    []models.Type{{Id: 2}},
	},
	{
		Name:     "Charmeleon",
		Info:     "Charmeleon mercilessly destroys its foes using its sharp claws. If it encounters a strong foe, it turns aggressive. In this excited state, the flame at the tip of its tail flares with a bluish white color.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/005.png",
		Types:    []models.Type{{Id: 2}},
	},
	{
		Name:     "Charizard",
		Info:     "Charizard flies around the sky in search of powerful opponents. It breathes fire of such great heat that it melts anything. However, it never turns its fiery breath on any opponent weaker than itself.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/006.png",
		Types:    []models.Type{{Id: 2}, {Id: 10}},
	},
	{
		Name:     "Squirtle",
		Info:     "Squirtle's shell is not merely used for protection. The shell's rounded shape and the grooves on its surface help minimize resistance in water, enabling this Pokémon to swim at high speeds.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/007.png",
		Types:    []models.Type{{Id: 3}},
	},
	{
		Name:     "Wartortle",
		Info:     "Its tail is large and covered with a rich, thick fur. The tail becomes increasingly deeper in color as Wartortle ages. The scratches on its shell are evidence of this Pokémon's toughness as a battler.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/008.png",
		Types:    []models.Type{{Id: 3}},
	},
	{
		Name:     "Blastoise",
		Info:     "Blastoise has water spouts that protrude from its shell. The water spouts are very accurate. They can shoot bullets of water with enough accuracy to strike empty cans from a distance of over 160 feet.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/009.png",
		Types:    []models.Type{{Id: 3}},
	},
	{
		Name:     "Caterpie",
		Info:     "Caterpie has a voracious appetite. It can devour leaves bigger than its body right before your eyes. From its antenna, this Pokémon releases a terrifically strong odor.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/010.png",
		Types:    []models.Type{{Id: 12}},
	},
	{
		Name:     "Metapod",
		Info:     "The shell covering this Pokémon's body is as hard as an iron slab. Metapod does not move very much. It stays still because it is preparing its soft innards for evolution inside the hard shell.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/011.png",
		Types:    []models.Type{{Id: 12}},
	},
	{
		Name:     "Butterfree",
		Info:     "Butterfree has a superior ability to search for delicious honey from flowers. It can even search out, extract, and carry honey from flowers that are blooming over six miles from its nest.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/012.png",
		Types:    []models.Type{{Id: 12}, {Id: 10}},
	},
	{
		Name:     "Weedle",
		Info:     "Weedle has an extremely acute sense of smell. It distinguishes its favorite kinds of leaves from those it dislikes by sniffing with its big red proboscis (nose).",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/013.png",
		Types:    []models.Type{{Id: 12}, {Id: 8}},
	},
	{
		Name:     "Kakuna",
		Info:     "Kakuna remains virtually immobile as it clings to a tree. However, on the inside, it is extremely busy as it prepares for its coming evolution. This is evident from how hot the shell becomes to the touch.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/014.png",
		Types:    []models.Type{{Id: 12}, {Id: 8}},
	},
	{
		Name:     "Beedrill",
		Info:     "Beedrill is extremely territorial. No one should ever approach its nest—this is for their own safety. If angered, they will attack in a furious swarm.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/015.png",
		Types:    []models.Type{{Id: 12}, {Id: 8}},
	},
	{
		Name:     "Pidgey",
		Info:     "Pidgey has an extremely sharp sense of direction. It is capable of unerringly returning home to its nest, however far it may be removed from its familiar surroundings.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/016.png",
		Types:    []models.Type{{Id: 1}, {Id: 10}},
	},
	{
		Name:     "Pidgeotto",
		Info:     "Pidgeotto claims a large area as its own territory. This Pokémon flies around, patrolling its living space. If its territory is violated, it shows no mercy in thoroughly punishing the foe with its sharp claws.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/017.png",
		Types:    []models.Type{{Id: 1}, {Id: 10}},
	},
	{
		Name:     "Pidgeot",
		Info:     "This Pokémon has a dazzling plumage of beautifully glossy feathers. Many Trainers are captivated by the striking beauty of the feathers on its head, compelling them to choose Pidgeot as their Pokémon.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/018.png",
		Types:    []models.Type{{Id: 1}, {Id: 10}},
	},
	{
		Name:     "Rattata",
		Info:     "Rattata is cautious in the extreme. Even while it is asleep, it constantly listens by moving its ears around. It is not picky about where it lives—it will make its nest anywhere.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/019.png",
		Types:    []models.Type{{Id: 1}},
	},
	{
		Name:     "Raticate",
		Info:     "Raticate’s sturdy fangs grow steadily. To keep them ground down, it gnaws on rocks and logs. It may even chew on the walls of houses.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/020.png",
		Types:    []models.Type{{Id: 1}},
	},
	{
		Name:     "Spearow",
		Info:     "Spearow has a very loud cry that can be heard over half a mile away. If its high, keening cry is heard echoing all around, it is a sign that they are warning each other of danger.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/021.png",
		Types:    []models.Type{{Id: 1}, {Id: 10}},
	},
	{
		Name:     "Fearow",
		Info:     "Fearow is recognized by its long neck and elongated beak. They are conveniently shaped for catching prey in soil or water. It deftly moves its long and skinny beak to pluck prey.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/022.png",
		Types:    []models.Type{{Id: 1}, {Id: 10}},
	},
	{
		Name:     "Ekans",
		Info:     "Ekans curls itself up in a spiral while it rests. Assuming this position allows it to quickly respond to a threat from any direction with a glare from its upraised head.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/023.png",
		Types:    []models.Type{{Id: 8}},
	},
	{
		Name:     "Arbok",
		Info:     "This Pokémon is terrifically strong in order to constrict things with its body. It can even flatten steel oil drums. Once Arbok wraps its body around its foe, escaping its crunching embrace is impossible.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/024.png",
		Types:    []models.Type{{Id: 8}},
	},
	{
		Name:     "Pikachu",
		Info:     "Whenever Pikachu comes across something new, it blasts it with a jolt of electricity. If you come across a blackened berry, it's evidence that this Pokémon mistook the intensity of its charge.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/025.png",
		Types:    []models.Type{{Id: 4}},
	},
	{
		Name:     "Raichu",
		Info:     "If the electrical sacs become excessively charged, Raichu plants its tail in the ground and discharges. Scorched patches of ground will be found near this Pokémon's nest.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/026.png",
		Types:    []models.Type{{Id: 4}},
	},
	{
		Name:     "Sandshrew",
		Info:     "Sandshrew's body is configured to absorb water without waste, enabling it to survive in an arid desert. This Pokémon curls up to protect itself from its enemies.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/027.png",
		Types:    []models.Type{{Id: 9}},
	},
	{
		Name:     "Sandslash",
		Info:     "Sandslash's body is covered by tough spikes, which are hardened sections of its hide. Once a year, the old spikes fall out, to be replaced with new spikes that grow out from beneath the old ones.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/028.png",
		Types:    []models.Type{{Id: 9}},
	},
	{
		Name:     "Nidoran♀",
		Info:     "Nidoran♀ has barbs that secrete a powerful poison. They are thought to have developed as protection for this small-bodied Pokémon. When enraged, it releases a horrible toxin from its horn.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/029.png",
		Types:    []models.Type{{Id: 8}},
	},
	{
		Name:     "Nidorina",
		Info:     "When Nidorina are with their friends or family, they keep their barbs tucked away to prevent hurting each other. This Pokémon appears to become nervous if separated from the others.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/030.png",
		Types:    []models.Type{{Id: 8}},
	},
	{
		Name:     "Nidoqueen",
		Info:     "Nidoqueen's body is encased in extremely hard scales. It is adept at sending foes flying with harsh tackles. This Pokémon is at its strongest when it is defending its young.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/031.png",
		Types:    []models.Type{{Id: 8}, {Id: 9}},
	},
	{
		Name:     "Nidoran♂",
		Info:     "Nidoran♂ has developed muscles for moving its ears. Thanks to them, the ears can be freely moved in any direction. Even the slightest sound does not escape this Pokémon's notice.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/032.png",
		Types:    []models.Type{{Id: 8}},
	},
	{
		Name:     "Nidorino",
		Info:     "Nidorino has a horn that is harder than a diamond. If it senses a hostile presence, all the barbs on its back bristle up at once, and it challenges the foe with all its might.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/033.png",
		Types:    []models.Type{{Id: 8}},
	},
	{
		Name:     "Nidoking",
		Info:     "Nidoking's thick tail packs enormously destructive power. With one swing, it can topple a metal transmission tower. Once this Pokémon goes on a rampage, there is no stopping it.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/034.png",
		Types:    []models.Type{{Id: 8}, {Id: 9}},
	},
	{
		Name:     "Clefairy",
		Info:     "Clefairy moves by skipping lightly as if it were flying using its wings. Its bouncy step lets it even walk on water. On quiet, moonlit nights, it strolls on lakes.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/035.png",
		Types:    []models.Type{{Id: 18}},
	},
	{
		Name:     "Clefable",
		Info:     "Clefable moves by skipping lightly as if it were flying using its wings. Its bouncy step lets it even walk on water. On quiet, moonlit nights, it strolls on lakes.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/036.png",
		Types:    []models.Type{{Id: 18}},
	},
	{
		Name:     "Vulpix",
		Info:     "Vulpix has a flame inside its body that never goes out. During the daytime, when the temperatures rise, this Pokémon releases flames from its mouth to prevent its body from growing too hot.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/037.png",
		Types:    []models.Type{{Id: 2}},
	},
	{
		Name:     "Ninetales",
		Info:     "Ninetales casts a sinister light from its bright red eyes to gain total control over its foe's mind. This Pokémon is said to live for a thousand years.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/038.png",
		Types:    []models.Type{{Id: 2}},
	},
	{
		Name:     "Jigglypuff",
		Info:     "Jigglypuff's vocal cords can freely adjust the wavelength of its voice. This Pokémon uses this ability to sing at precisely the right wavelength to make its foes most drowsy.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/039.png",
		Types:    []models.Type{{Id: 1}, {Id: 18}},
	},
	{
		Name:     "Wigglytuff",
		Info:     "Wigglytuff's body is very flexible. By inhaling deeply, this Pokémon can inflate itself seemingly without end. Once inflated, Wigglytuff bounces along lightly like a balloon.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/040.png",
		Types:    []models.Type{{Id: 1}, {Id: 18}},
	},
	{
		Name:     "Zubat",
		Info:     "Zubat remains quietly unmoving in a dark spot during the bright daylight hours. It does so because prolonged exposure to the sun causes its body to become slightly burned.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/041.png",
		Types:    []models.Type{{Id: 8}, {Id: 10}},
	},
	{
		Name:     "Golbat",
		Info:     "Golbat loves to drink the blood of living things. It is particularly active in the pitch black of night. This Pokémon flits around in the night skies, seeking fresh blood.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/042.png",
		Types:    []models.Type{{Id: 8}, {Id: 10}},
	},
	{
		Name:     "Oddish",
		Info:     "Oddish searches for fertile, nutrient-rich soil, then plants itself. During the daytime, while it is planted, this Pokémon's feet are thought to change shape and become similar to the roots of trees.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/043.png",
		Types:    []models.Type{{Id: 5}, {Id: 8}},
	},
	{
		Name:     "Gloom",
		Info:     "Gloom releases a foul fragrance from the pistil of its flower. When faced with danger, the stench worsens. If this Pokémon is feeling calm and secure, it does not release its usual stinky aroma.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/044.png",
		Types:    []models.Type{{Id: 5}, {Id: 8}},
	},
	{
		Name:     "Vileplume",
		Info:     "Vileplume has the world's largest petals. They are used to attract prey that are then doused with toxic spores. Once the prey are immobilized, this Pokémon catches and devours them.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/045.png",
		Types:    []models.Type{{Id: 5}, {Id: 8}},
	},
	{
		Name:     "Paras",
		Info:     "Paras has parasitic mushrooms growing on its back called tochukaso. They grow large by drawing nutrients from this Bug Pokémon host. They are highly valued as a medicine for extending life.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/046.png",
		Types:    []models.Type{{Id: 12}, {Id: 5}},
	},
	{
		Name:     "Parasect",
		Info:     "Parasect is known to infest large trees en masse and drain nutrients from the lower trunk and roots. When an infested tree dies, they move onto another tree all at once.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/047.png",
		Types:    []models.Type{{Id: 12}, {Id: 5}},
	},
	{
		Name:     "Venonat",
		Info:     "Venonat is said to have evolved with a coat of thin, stiff hair that covers its entire body for protection. It possesses large eyes that never fail to spot even minuscule prey.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/048.png",
		Types:    []models.Type{{Id: 12}, {Id: 8}},
	},
	{
		Name:     "Venomoth",
		Info:     "Venomoth is nocturnal—it is a Pokémon that only becomes active at night. Its favorite prey are small insects that gather around streetlights, attracted by the light in the darkness.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/049.png",
		Types:    []models.Type{{Id: 12}, {Id: 8}},
	},
	{
		Name:     "Diglett",
		Info:     "Diglett are raised in most farms. The reason is simple—wherever this Pokémon burrows, the soil is left perfectly tilled for planting crops. This soil is made ideal for growing delicious vegetables.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/050.png",
		Types:    []models.Type{{Id: 9}},
	},
	{
		Name:     "Dugtrio",
		Info:     "Dugtrio are actually triplets that emerged from one body. As a result, each triplet thinks exactly like the other two triplets. They work cooperatively to burrow endlessly.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/051.png",
		Types:    []models.Type{{Id: 9}},
	},
	{
		Name:     "Meowth",
		Info:     "Meowth withdraws its sharp claws into its paws to slinkily sneak about without making any incriminating footsteps. For some reason, this Pokémon loves shiny coins that glitter with light.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/052.png",
		Types:    []models.Type{{Id: 1}},
	},
	{
		Name:     "Persian",
		Info:     "Persian has six bold whiskers that give it a look of toughness. The whiskers sense air movements to determine what is in the Pokémon's surrounding vicinity. It becomes docile if grabbed by the whiskers.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/053.png",
		Types:    []models.Type{{Id: 1}},
	},
	{
		Name:     "Psyduck",
		Info:     "Psyduck is constantly beset by headaches. If the Pokémon lets its strange power erupt, apparently the pain subsides for a while. This Pokémon's power seems to increase when it is confused.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/054.png",
		Types:    []models.Type{{Id: 3}},
	},
	{
		Name:     "Golduck",
		Info:     "The webbed flippers on its forelegs and hind legs and the streamlined body of Golduck give it frightening speed. This Pokémon is definitely much faster than even the most athletic swimmer.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/055.png",
		Types:    []models.Type{{Id: 3}},
	},
	{
		Name:     "Mankey",
		Info:     "When Mankey starts shaking and its nasal breathing turns rough, it's a sure sign that it is becoming angry. However, because it goes into a towering rage almost instantly, it is impossible for anyone to flee its wrath.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/056.png",
		Types:    []models.Type{{Id: 7}},
	},
	{
		Name:     "Primeape",
		Info:     "When Primeape becomes furious, its blood circulation is boosted. In turn, its muscles are made even stronger. However, it also becomes much less intelligent at the same time.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/057.png",
		Types:    []models.Type{{Id: 7}},
	},
	{
		Name:     "Growlithe",
		Info:     "Growlithe has a superb sense of smell. Once it smells anything, this Pokémon won't forget the scent, no matter what. It uses its advanced olfactory sense to determine the emotions of other living things.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/058.png",
		Types:    []models.Type{{Id: 2}},
	},
	{
		Name:     "Arcanine",
		Info:     "Arcanine is known for its high speed. It is said to be capable of running over 6,200 miles in a single day and night. The fire that blazes wildly within this Pokémon's body is its source of power.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/059.png",
		Types:    []models.Type{{Id: 2}},
	},
	{
		Name:     "Poliwag",
		Info:     "Poliwag has a very thin skin. It is possible to see the Pokémon's spiral innards right through the skin. Despite its thinness, however, the skin is also very flexible. Even sharp fangs bounce right off it.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/060.png",
		Types:    []models.Type{{Id: 3}},
	},
	{
		Name:     "Poliwhirl",
		Info:     "Poliwhirl's two legs are well developed. Even though it can live on the ground, it prefers living in water. It is always floating in the water.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/061.png",
		Types:    []models.Type{{Id: 3}},
	},
	{
		Name:     "Poliwrath",
		Info:     "Poliwrath's highly developed, brawny muscles never grow fatigued, however much it exercises. It is so tirelessly strong, this Pokémon can swim back and forth across the ocean without effort.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/062.png",
		Types:    []models.Type{{Id: 3}, {Id: 7}},
	},
	{
		Name:     "Abra",
		Info:     "Abra needs to sleep for eighteen hours a day. If it doesn't, this Pokémon loses its ability to use telekinetic powers. If it is attacked, Abra escapes using Teleport while it is still sleeping.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/063.png",
		Types:    []models.Type{{Id: 11}},
	},
	{
		Name:     "Kadabra",
		Info:     "Kadabra emits a peculiar alpha wave if it develops a headache. Only those people with a particularly strong psyche can hope to become a Trainer of this Pokémon.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/064.png",
		Types:    []models.Type{{Id: 11}},
	},
	{
		Name:     "Alakazam",
		Info:     "Alakazam's brain continually grows, making its head far too heavy to support with its neck. This Pokémon holds its head up using its psychokinetic power instead.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/065.png",
		Types:    []models.Type{{Id: 11}},
	},
	{
		Name:     "Machop",
		Info:     "Machop's muscles are special—they never get sore no matter how much they are used in exercise. This Pokémon has sufficient power to hurl a hundred adult humans.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/066.png",
		Types:    []models.Type{{Id: 7}},
	},
	{
		Name:     "Machoke",
		Info:     "Machoke's thoroughly toned muscles possess the hardness of steel. This Pokémon has so much strength, it can easily hold aloft a sumo wrestler on just one finger.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/067.png",
		Types:    []models.Type{{Id: 7}},
	},
	{
		Name:     "Machamp",
		Info:     "Machamp has the power to hurl anything aside. However, trying to do any work requiring care and dexterity causes its arms to get tangled. This Pokémon tends to leap into action before it thinks.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/068.png",
		Types:    []models.Type{{Id: 7}},
	},
	{
		Name:     "Bellsprout",
		Info:     "Bellsprout's thin and flexible body lets it bend and sway to avoid any attack, however strong it may be. From its mouth, this Pokémon spits a corrosive fluid that melts even iron.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/069.png",
		Types:    []models.Type{{Id: 5}, {Id: 8}},
	},
	{
		Name:     "Weepinbell",
		Info:     "Weepinbell has a large hook on its rear end. At night, the Pokémon hooks on to a tree branch and goes to sleep. If it moves around in its sleep, it may wake up to find itself on the ground.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/070.png",
		Types:    []models.Type{{Id: 5}, {Id: 8}},
	},
	{
		Name:     "Victreebel",
		Info:     "Victreebel has a long vine that extends from its head. This vine is waved and flicked about as if it were an animal to attract prey. When an unsuspecting prey draws near, this Pokémon swallows it whole.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/071.png",
		Types:    []models.Type{{Id: 5}, {Id: 8}},
	},
	{
		Name:     "Tentacool",
		Info:     "Tentacool absorbs sunlight and refracts it using water inside its body to convert it into beam energy. This Pokémon shoots beams from the small round organ above its eyes.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/072.png",
		Types:    []models.Type{{Id: 3}, {Id: 8}},
	},
	{
		Name:     "Tentacruel",
		Info:     "Tentacruel has large red orbs on its head. The orbs glow before lashing the vicinity with a harsh ultrasonic blast. This Pokémon's outburst creates rough waves around it.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/073.png",
		Types:    []models.Type{{Id: 3}, {Id: 8}},
	},
	{
		Name:     "Geodude",
		Info:     "The longer a Geodude lives, the more its edges are chipped and worn away, making it more rounded in appearance. However, this Pokémon's heart will remain hard, craggy, and rough always.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/074.png",
		Types:    []models.Type{{Id: 13}, {Id: 9}},
	},
	{
		Name:     "Graveler",
		Info:     "Graveler grows by feeding on rocks. Apparently, it prefers to eat rocks that are covered in moss. This Pokémon eats its way through a ton of rocks on a daily basis.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/075.png",
		Types:    []models.Type{{Id: 13}, {Id: 9}},
	},
	{
		Name:     "Golem",
		Info:     "Golem live up on mountains. If there is a large earthquake, these Pokémon will come rolling down off the mountains en masse to the foothills below.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/076.png",
		Types:    []models.Type{{Id: 13}, {Id: 9}},
	},
	{
		Name:     "Ponyta",
		Info:     "Ponyta is very weak at birth. It can barely stand up. This Pokémon becomes stronger by stumbling and falling to keep up with its parent.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/077.png",
		Types:    []models.Type{{Id: 2}},
	},
	{
		Name:     "Rapidash",
		Info:     "Rapidash usually can be seen casually cantering in the fields and plains. However, when this Pokémon turns serious, its fiery manes flare and blaze as it gallops its way up to 150 mph.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/078.png",
		Types:    []models.Type{{Id: 2}},
	},
	{
		Name:     "Slowpoke",
		Info:     "Slowpoke uses its tail to catch prey by dipping it in water at the side of a river. However, this Pokémon often forgets what it's doing and often spends entire days just loafing at water's edge.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/079.png",
		Types:    []models.Type{{Id: 3}, {Id: 11}},
	},
	{
		Name:     "Slowbro",
		Info:     "Slowbro's tail has a Shellder firmly attached with a bite. As a result, the tail can't be used for fishing anymore. This causes Slowbro to grudgingly swim and catch prey instead.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/080.png",
		Types:    []models.Type{{Id: 3}, {Id: 11}},
	},
	{
		Name:     "Magnemite",
		Info:     "Magnemite attaches itself to power lines to feed on electricity. If your house has a power outage, check your circuit breakers. You may find a large number of this Pokémon clinging to the breaker box.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/081.png",
		Types:    []models.Type{{Id: 4}, {Id: 17}},
	},
	{
		Name:     "Magneton",
		Info:     "Magneton emits a powerful magnetic force that is fatal to electronics and precision instruments. Because of this, it is said that some towns warn people to keep this Pokémon inside a Poké Ball.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/082.png",
		Types:    []models.Type{{Id: 4}, {Id: 17}},
	},
	{
		Name:     "Farfetch'd",
		Info:     "Farfetch'd is always seen with a stalk from a plant of some sort. Apparently, there are good stalks and bad stalks. This Pokémon has been known to fight with others over stalks.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/083.png",
		Types:    []models.Type{{Id: 1}, {Id: 10}},
	},
	{
		Name:     "Doduo",
		Info:     "Doduo's two heads contain completely identical brains. A scientific study reported that on rare occasions, there will be examples of this Pokémon possessing different sets of brains.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/084.png",
		Types:    []models.Type{{Id: 1}, {Id: 10}},
	},
	{
		Name:     "Dodrio",
		Info:     "Apparently, the heads aren't the only parts of the body that Dodrio has three of. It has three sets of hearts and lungs as well, so it is capable of running long distances without rest.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/085.png",
		Types:    []models.Type{{Id: 1}, {Id: 10}},
	},
	{
		Name:     "Seel",
		Info:     "Seel hunts for prey in the frigid sea underneath sheets of ice. When it needs to breathe, it punches a hole through the ice with the sharply protruding section of its head.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/086.png",
		Types:    []models.Type{{Id: 3}},
	},
	{
		Name:     "Dewgong",
		Info:     "Dewgong loves to snooze on bitterly cold ice. The sight of this Pokémon sleeping on a glacier was mistakenly thought to be a mermaid by a mariner long ago.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/087.png",
		Types:    []models.Type{{Id: 3}, {Id: 6}},
	},
	{
		Name:     "Grimer",
		Info:     "Grimer emerged from the sludge that settled on a polluted seabed. This Pokémon loves anything filthy. It constantly leaks a horribly germ-infested fluid from all over its body.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/088.png",
		Types:    []models.Type{{Id: 8}},
	},
	{
		Name:     "Muk",
		Info:     "From Muk’s body seeps a foul fluid that gives off a nose-bendingly horrible stench. Just one drop of this Pokémon’s body fluid can turn a pool stagnant and rancid.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/089.png",
		Types:    []models.Type{{Id: 8}},
	},
	{
		Name:     "Shellder",
		Info:     "Shellder’s hard shell repels any kind of attack. It is vulnerable only when its shell is open, exposing its weak points.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/090.png",
		Types:    []models.Type{{Id: 3}},
	},
	{
		Name:     "Cloyster",
		Info:     "Cloyster fights by closing its shell tightly and launching its shell spikes at foes. This Pokémon is also known as the ‘Bivalve Pokémon.’",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/091.png",
		Types:    []models.Type{{Id: 3}, {Id: 6}},
	},
	{
		Name:     "Gastly",
		Info:     "Gastly is largely composed of gaseous matter. When exposed to a strong wind, the gaseous body quickly dwindles away. Groups of this Pokémon cluster under the eaves of houses to escape the ravages of wind.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/092.png",
		Types:    []models.Type{{Id: 14}, {Id: 8}},
	},
	{
		Name:     "Haunter",
		Info:     "Haunter is a dangerous Pokémon. If one beckons you while floating in darkness, you must never approach it. This Pokémon will try to lick you with its tongue and steal your life away.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/093.png",
		Types:    []models.Type{{Id: 14}, {Id: 8}},
	},
	{
		Name:     "Gengar",
		Info:     "Sometimes, on a dark night, your shadow thrown by a streetlight will suddenly and startlingly overtake you. It is actually a Gengar running past you, pretending to be your shadow.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/094.png",
		Types:    []models.Type{{Id: 14}, {Id: 8}},
	},
	{
		Name:     "Onix",
		Info:     "Onix has a magnet in its brain. It acts as a compass so that this Pokémon does not lose direction while it is tunneling. As it grows older, its body becomes increasingly rounder and smoother.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/095.png",
		Types:    []models.Type{{Id: 13}, {Id: 9}},
	},
	{
		Name:     "Drowzee",
		Info:     "If your nose becomes itchy while you are sleeping, it’s a sure sign that one of these Pokémon is standing above your pillow and trying to eat your dream through your nostrils.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/096.png",
		Types:    []models.Type{{Id: 11}},
	},
	{
		Name:     "Hypno",
		Info:     "Hypno holds a pendulum in its hand. The arcing movement and glitter of the pendulum lull the foe into a deep state of hypnosis. While this Pokémon searches for prey, it polishes the pendulum.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/097.png",
		Types:    []models.Type{{Id: 11}},
	},
	{
		Name:     "Krabby",
		Info:     "Krabby live on beaches, burrowed inside holes dug into the sand. On sandy beaches with little in the way of food, these Pokémon can be seen squabbling with each other over territory.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/098.png",
		Types:    []models.Type{{Id: 3}},
	},
	{
		Name:     "Kingler",
		Info:     "Kingler has an enormous, oversized claw. It waves this huge claw in the air to communicate with others. However, because the claw is so heavy, the Pokémon quickly tires.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/099.png",
		Types:    []models.Type{{Id: 3}},
	},
	{
		Name:     "Voltorb",
		Info:     "Voltorb was first sighted at a company that manufactures Poké Balls. The link between that sighting and the fact that this Pokémon looks very similar to a Poké Ball remains a mystery.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/100.png",
		Types:    []models.Type{{Id: 4}},
	},
	{
		Name:     "Electrode",
		Info:     "Electrode eats electricity in the atmosphere. On days when lightning strikes, you can see this Pokémon exploding all over the place from eating too much electricity.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/101.png",
		Types:    []models.Type{{Id: 4}},
	},
	{
		Name:     "Exeggcute",
		Info:     "Exeggcute gather together in a village of approximately six eggs. The heads of each egg communicate with each other by using a telepathic wave.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/102.png",
		Types:    []models.Type{{Id: 5}, {Id: 11}},
	},
	{
		Name:     "Exeggutor",
		Info:     "Exeggutor originally came from the tropics. Its heads steadily grow larger from exposure to strong sunlight. It is said that when the heads fall off, they group together to form Exeggcute.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/103.png",
		Types:    []models.Type{{Id: 5}, {Id: 11}},
	},
	{
		Name:     "Cubone",
		Info:     "Cubone pines for the mother it will never see again. Seeing a likeness of its mother in the full moon, it cries. The stains on the skull it wears are made by the tears it sheds.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/104.png",
		Types:    []models.Type{{Id: 9}},
	},
	{
		Name:     "Marowak",
		Info:     "Marowak is the evolved form of a Cubone that has overcome its sadness at the loss of its mother and grown tough. This Pokémon’s tempered and hardened spirit is not easily broken.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/105.png",
		Types:    []models.Type{{Id: 9}},
	},
	{
		Name:     "Hitmonlee",
		Info:     "Hitmonlee’s legs freely contract and stretch. Using these springlike legs, it bowls over foes with devastating kicks. After battle, it rubs down its legs and loosens the muscles to overcome fatigue.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/106.png",
		Types:    []models.Type{{Id: 7}},
	},
	{
		Name:     "Hitmonchan",
		Info:     "Hitmonchan is said to possess the spirit of a boxer who had been working toward a world championship. This Pokémon has an indomitable spirit and will never give up in the face of adversity.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/107.png",
		Types:    []models.Type{{Id: 7}},
	},
	{
		Name:     "Lickitung",
		Info:     "Whenever Lickitung comes across something new, it will unfailingly give it a lick. It does so because it memorizes things by texture and by taste. It is somewhat put off by sour things.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/108.png",
		Types:    []models.Type{{Id: 1}},
	},
	{
		Name:     "Koffing",
		Info:     "If Koffing becomes agitated, it raises the toxicity of its internal gases and then jets them out from all over its body. This Pokémon may also overinflate its round body, then explode.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/109.png",
		Types:    []models.Type{{Id: 8}},
	},
	{
		Name:     "Weezing",
		Info:     "Weezing loves the gases given off by rotted kitchen garbage. This Pokémon will find a dirty, unkempt house and make it its home. At night, when the people in the house are asleep, it will go through the trash.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/110.png",
		Types:    []models.Type{{Id: 8}},
	},
	{
		Name:     "Rhyhorn",
		Info:     "Rhyhorn’s brain is very small. It is so dense, while on a run it forgets why it started running in the first place. It apparently remembers sometimes if it demolishes something.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/111.png",
		Types:    []models.Type{{Id: 9}, {Id: 13}},
	},
	{
		Name:     "Rhydon",
		Info:     "Rhydon has a horn that serves as a drill. It is used for destroying rocks and boulders. This Pokémon occasionally rams into streams of magma, but the armor-like hide prevents it from feeling the heat.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/112.png",
		Types:    []models.Type{{Id: 9}, {Id: 13}},
	},
	{
		Name:     "Chansey",
		Info:     "Chansey lays nutritionally excellent eggs every day. The eggs are so delicious, they are easily and eagerly devoured by even those people who have lost their appetite.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/113.png",
		Types:    []models.Type{{Id: 1}},
	},
	{
		Name:     "Tangela",
		Info:     "Tangela’s vines snap off easily if they are grabbed. This happens without pain, allowing it to make a quick getaway. The lost vines are replaced by newly grown vines the very next day.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/114.png",
		Types:    []models.Type{{Id: 5}},
	},
	{
		Name:     "Kangaskhan",
		Info:     "Kangaskhan protects its child by keeping it in its pouch. It has zero interest in the lives of humans. As soon as a baby is born, it will begin to evolve into an adult.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/115.png",
		Types:    []models.Type{{Id: 1}},
	},
	{
		Name:     "Horsea",
		Info:     "Horsea eats small insects and moss off of rocks. If the ocean current turns fast, this Pokémon anchors itself by wrapping its tail around rocks or coral to prevent being washed away.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/116.png",
		Types:    []models.Type{{Id: 3}},
	},
	{
		Name:     "Seadra",
		Info:     "Seadra sleeps after wriggling itself between the branches of coral. Those trying to harvest coral are occasionally stung by this Pokémon’s poison barbs if they fail to notice it.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/117.png",
		Types:    []models.Type{{Id: 3}},
	},
	{
		Name:     "Goldeen",
		Info:     "Goldeen is a very beautiful Pokémon with fins that billow elegantly in water. However, don’t let your guard down around this Pokémon—it could ram you powerfully with its horn.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/118.png",
		Types:    []models.Type{{Id: 3}},
	},
	{
		Name:     "Seaking",
		Info:     "Seaking is very protective of its eggs. The male and female will take turns patrolling around their nest and eggs. The guarding of eggs by these Pokémon goes on for over a month.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/119.png",
		Types:    []models.Type{{Id: 3}},
	},
	{
		Name:     "Staryu",
		Info:     "Staryu apparently communicates with the stars in the night sky by flashing the red core at the center of its body. If parts of its body are torn, this Pokémon simply regenerates the missing pieces and limbs.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/120.png",
		Types:    []models.Type{{Id: 3}},
	},
	{
		Name:     "Starmie",
		Info:     "Starmie’s center section—the core—glows brightly in seven colors. Because of its luminous nature, this Pokémon has been given the nickname “the gem of the sea.”",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/121.png",
		Types:    []models.Type{{Id: 3}, {Id: 11}},
	},
	{
		Name:     "Mr. Mime",
		Info:     "Mr. Mime is a master of pantomime. Its gestures and motions convince watchers that something unseeable actually exists. Once the watchers are convinced, the unseeable thing exists as if it were real.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/122.png",
		Types:    []models.Type{{Id: 11}, {Id: 18}},
	},
	{
		Name:     "Scyther",
		Info:     "Scyther is blindingly fast. Its blazing speed enhances the effectiveness of the twin scythes on its forearms. This Pokémon’s scythes are so effective, they can slice through thick logs in one wicked stroke.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/123.png",
		Types:    []models.Type{{Id: 12}, {Id: 10}},
	},
	{
		Name:     "Jynx",
		Info:     "Jynx walks rhythmically, swaying and shaking its hips as if it were dancing. Its motions are so bouncingly alluring, people seeing it are compelled to shake their hips without giving any thought to what they are doing.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/124.png",
		Types:    []models.Type{{Id: 6}, {Id: 11}},
	},
	{
		Name:     "Electabuzz",
		Info:     "Electabuzz’s body constantly discharges electricity. Getting close to it will make your hair stand on end. It is said to abscond with prey by flashing the lightning on its tail.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/125.png",
		Types:    []models.Type{{Id: 4}},
	},
	{
		Name:     "Magmar",
		Info:     "Magmar dispatches its prey with fire. But it regrets this habit once it realizes that it has burned its intended prey to a charred crisp.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/126.png",
		Types:    []models.Type{{Id: 2}},
	},
	{
		Name:     "Pinsir",
		Info:     "Pinsir has a pair of massive horns. Protruding from the surface of these horns are thorns. These thorns are driven deeply into the foe’s body when the pincer closes, making it tough for the foe to escape.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/127.png",
		Types:    []models.Type{{Id: 12}},
	},
	{
		Name:     "Tauros",
		Info:     "This Pokémon is not satisfied unless it is rampaging at all times. If there is no opponent for Tauros to battle, it will charge at thick trees and knock them down to calm itself.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/128.png",
		Types:    []models.Type{{Id: 1}},
	},
	{
		Name:     "Magikarp",
		Info:     "Magikarp is virtually useless in battle as it can only splash around. As a result, it is considered to be weak. However, it is actually a very hardy Pokémon that can survive in any body of water no matter how polluted it is.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/129.png",
		Types:    []models.Type{{Id: 3}},
	},
	{
		Name:     "Gyarados",
		Info:     "Gyarados is a very vengeful Pokémon that flies into uncontrollable rage when it is provoked. It will not calm down until it has shed the blood of its foe.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/130.png",
		Types:    []models.Type{{Id: 3}, {Id: 10}},
	},
	{
		Name:     "Lapras",
		Info:     "People have driven Lapras almost to the point of extinction. In the evenings, it is said to sing plaintively as it seeks what few others of its kind still remain.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/131.png",
		Types:    []models.Type{{Id: 3}, {Id: 6}},
	},
	{
		Name:     "Ditto",
		Info:     "Ditto rearranges its cell structure to transform itself into other shapes. However, if it tries to transform itself into something by relying on its memory, this Pokémon manages to get details wrong.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/132.png",
		Types:    []models.Type{{Id: 1}},
	},
	{
		Name:     "Eevee",
		Info:     "Eevee has an unstable genetic makeup that suddenly mutates due to the environment in which it lives. Radiation from various stones causes this Pokémon to evolve.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/133.png",
		Types:    []models.Type{{Id: 1}},
	},
	{
		Name:     "Vaporeon",
		Info:     "Vaporeon underwent a spontaneous mutation and grew fins and gills that allow it to live underwater. This Pokémon has the ability to freely control water.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/134.png",
		Types:    []models.Type{{Id: 3}},
	},
	{
		Name:     "Jolteon",
		Info:     "Jolteon’s cells generate a low level of electricity. This power is amplified by the static electricity of its fur, enabling the Pokémon to drop thunderbolts. The bristling fur is made of electrically charged needles.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/135.png",
		Types:    []models.Type{{Id: 4}},
	},
	{
		Name:     "Flareon",
		Info:     "Flareon’s fluffy fur has a functional purpose—it releases heat into the air so that its body does not get excessively hot. This Pokémon’s body temperature can rise to a maximum of 1,650 degrees Fahrenheit.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/136.png",
		Types:    []models.Type{{Id: 2}},
	},
	{
		Name:     "Porygon",
		Info:     "Porygon is capable of reverting itself entirely back to program data and entering cyberspace. This Pokémon is copy protected so it cannot be duplicated by copying.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/137.png",
		Types:    []models.Type{{Id: 1}},
	},
	{
		Name:     "Omanyte",
		Info:     "Omanyte is one of the ancient and long-since-extinct Pokémon that have been regenerated from fossils by people. If attacked by an enemy, it withdraws itself inside its hard shell.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/138.png",
		Types:    []models.Type{{Id: 13}, {Id: 3}},
	},
	{
		Name:     "Omastar",
		Info:     "Omastar uses its tentacles to capture its prey. It is believed to have become extinct because its shell grew too large and heavy, causing its movements to become too slow and ponderous.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/139.png",
		Types:    []models.Type{{Id: 13}, {Id: 3}},
	},
	{
		Name:     "Kabuto",
		Info:     "Kabuto is a Pokémon that has been regenerated from a fossil. However, in extremely rare cases, living examples have been discovered. The Pokémon has not changed at all for 300 million years.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/140.png",
		Types:    []models.Type{{Id: 13}, {Id: 3}},
	},
	{
		Name:     "Kabutops",
		Info:     "Kabutops swam underwater to hunt for its prey in ancient times. The Pokémon was apparently evolving from being a water dweller to living on land as evident from the beginnings of change in its gills and legs.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/141.png",
		Types:    []models.Type{{Id: 13}, {Id: 3}},
	},
	{
		Name:     "Aerodactyl",
		Info:     "Aerodactyl is a Pokémon from the age of dinosaurs. It was regenerated from genetic material extracted from amber. It is imagined to have been the king of the skies in ancient times.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/142.png",
		Types:    []models.Type{{Id: 13}, {Id: 10}},
	},
	{
		Name:     "Snorlax",
		Info:     "Snorlax’s typical day consists of nothing more than eating and sleeping. It is such a docile Pokémon that there are children who use its expansive belly as a place to play.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/143.png",
		Types:    []models.Type{{Id: 1}},
	},
	{
		Name:     "Articuno",
		Info:     "Articuno is a legendary bird Pokémon that can control ice. The flapping of its wings chills the air. As a result, it is said that when this Pokémon flies, snow will fall.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/144.png",
		Types:    []models.Type{{Id: 6}, {Id: 10}},
	},
	{
		Name:     "Zapdos",
		Info:     "Zapdos is a legendary bird Pokémon that has the ability to control electricity. It usually lives in thunderclouds. The Pokémon gains power if it is stricken by lightning bolts.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/145.png",
		Types:    []models.Type{{Id: 4}, {Id: 10}},
	},
	{
		Name:     "Moltres",
		Info:     "Moltres is a legendary bird Pokémon that has the ability to control fire. If this Pokémon is injured, it is said to dip its body in the molten magma of a volcano to burn and heal itself.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/146.png",
		Types:    []models.Type{{Id: 2}, {Id: 10}},
	},
	{
		Name:     "Dratini",
		Info:     "Dratini continually molts and sloughs off its old skin. It does so because the life energy within its body steadily builds to reach uncontrollable levels.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/147.png",
		Types:    []models.Type{{Id: 15}},
	},
	{
		Name:     "Dragonair",
		Info:     "Dragonair stores an enormous amount of energy inside its body. It is said to alter weather conditions in its vicinity by discharging energy from the crystals on its neck and tail.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/148.png",
		Types:    []models.Type{{Id: 15}},
	},
	{
		Name:     "Dragonite",
		Info:     "Dragonite is capable of circling the globe in just 16 hours. It is a kindhearted Pokémon that leads lost and foundering ships in a storm to the safety of land.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/149.png",
		Types:    []models.Type{{Id: 15}, {Id: 10}},
	},
	{
		Name:     "Mewtwo",
		Info:     "Mewtwo is a Pokémon that was created by genetic manipulation. However, even though the scientific power of humans created this Pokémon’s body, they failed to endow Mewtwo with a compassionate heart.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/150.png",
		Types:    []models.Type{{Id: 11}},
	},
	{
		Name:     "Mew",
		Info:     "Mew is said to possess the genetic composition of all Pokémon. It is capable of making itself invisible at will, so it entirely avoids notice even if it approaches people.",
		PhotoUrl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/151.png",
		Types:    []models.Type{{Id: 11}},
	},
}
